name: check tiles

on:
  push:
    branches: [master]
    paths:
      - 'workers/tiles/**'
      - 'functions/**'
      # middleware функций берут код лимита отсюда
      - 'workers/guard/src/**'
      - '.github/workflows/check-tiles.yml'
  pull_request:
    paths:
      - 'workers/tiles/**'
      - 'functions/**'
      # middleware функций берут код лимита отсюда
      - 'workers/guard/src/**'
      - '.github/workflows/check-tiles.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: workers/tiles
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          node-version: '24'
          cache: npm
          cache-dependency-path: workers/tiles/package-lock.json
      - run: npm ci
      - run: npm test
